"""add user role

Revision ID: 67a073fbb2e2
Revises: 44280c390d0d
Create Date: 2026-09-24 16:00:14.149363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a073fbb2e2'
down_revision: Union[str, Sequence[str], None] = '44280c390d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('ps')

    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.String(),
            nullable=True,
            server_default='student'
        )
    )

    op.execute("UPDATE users SET role = 'student' WHERE role IS NULL")

    op.alter_column(
        'users',
        'role',
        nullable=False,
        server_default=None
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('ps',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('roll', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
